steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/my-app-image", "."]
  timeout: 600s

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/my-app-image"]

- name: "gcr.io/cloud-builders/gcloud"
  args: 
    - "run"
    - "deploy"
    - "my-cloud-run-service"
    - "--image"
    - "gcr.io/$PROJECT_ID/my-app-image"
    - "--platform"
    - "managed"
    - "--region"
    - "us-central1"
    - "--port"
    - "8080"
    - "--memory"
    - "512Mi"
    - "--allow-unauthenticated"
timeout: "1200s"
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'